on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: adafruit/ci-arduino
          path: ci
      - name: Install the prerequisites
        run: bash ci/actions_install.sh
      - name: Check for correct code formatting with clang-format
        run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .
        # Make sure to run the `clang-format -i src/*.h` on the repo.
        # To clean the Sources `clang-format -i examples/basic_use/basic_use.ino`

      - name: Test the code on supported platforms
        run: python3 ci/build_platform.py uno leonardo mega2560 feather32u4
